### ISSUE TITLE
D14 and A0 pin description silkscreen

### ISSUE THREAD

**Issue by Shinichi-Ohki** [kotobuki/Grove-Base-for-ESPr-Developer#1]
D14 と A0 のGroveコネクタのピン説明のシルクがそれぞれ
GND
3V3
D12
D14

GND
3V3
NC
TOUT
になっていますが、並び順が逆ではないですか。
D12とI2Cは合っています。

**Comment by kotobuki** [comment]
@Shinichi-Ohki 
ご指摘ありがとうございました。確かに並び順が間違っておりました。修正いたしました。

afea0fde9c1fa94f5626166e338421810012ed58
